# Generated by Django 3.2.5 on 2024-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Quotes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ruolo', models.CharField(max_length=1)),
                ('ruolo_desc', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('squadra', models.CharField(max_length=200)),
                ('quotazione_attuale', models.IntegerField()),
                ('quotazione_iniziale', models.IntegerField()),
            ],
        ),
    ]
