# Generated by Django 3.2.5 on 2024-08-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astatracking', '0003_alter_playerquotesfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stagione', models.CharField(max_length=250)),
                ('club', models.CharField(max_length=250)),
                ('presenze', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('autogoal', models.IntegerField()),
                ('subentrato', models.IntegerField()),
                ('sostituito', models.IntegerField()),
                ('ammonizioni', models.IntegerField()),
                ('espulsioni_doppiogiallo', models.IntegerField()),
                ('espulsioni_dirette', models.IntegerField()),
                ('rigori_segnati', models.IntegerField()),
                ('minuti_pergoal', models.IntegerField()),
                ('minuti_giocati', models.IntegerField()),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='astatracking.player_quotes')),
            ],
        ),
    ]
