# Generated by Django 3.2.5 on 2024-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astatracking', '0004_fullstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullstatistics',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fullstatistics',
            name='goal_subiti',
            field=models.IntegerField(default=0),
        ),
    ]
