# Generated by Django 3.2.5 on 2024-08-12 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astatracking', '0006_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crediti', models.IntegerField()),
                ('allenatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisti', to=settings.AUTH_USER_MODEL)),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisti', to='astatracking.player_quotes')),
            ],
        ),
    ]
