# Generated by Django 3.2.5 on 2024-08-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astatracking', '0007_acquisti'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticheFanta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruolo', models.CharField(max_length=250)),
                ('stagione', models.CharField(max_length=250)),
                ('squadra', models.CharField(max_length=250)),
                ('partiteavoto', models.IntegerField()),
                ('mediavoto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fantamedia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goalfatti', models.IntegerField()),
                ('goalsubiti', models.IntegerField()),
                ('rigoriparati', models.IntegerField()),
                ('ricoricalciati', models.IntegerField()),
                ('rigorisegnati', models.IntegerField()),
                ('rigorisbagliati', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('ammonizioni', models.IntegerField()),
                ('espulsioni', models.IntegerField()),
                ('autogoal', models.IntegerField()),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiche', to='astatracking.player_quotes')),
            ],
        ),
    ]
