# Generated by Django 3.2.5 on 2024-08-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astatracking', '0008_statistichefanta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistichefanta',
            old_name='ricoricalciati',
            new_name='rigoricalciati',
        ),
    ]
