# Generated by Django 3.2.5 on 2024-09-07 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astatracking', '0009_rename_ricoricalciati_statistichefanta_rigoricalciati'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstaOfferte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crediti', models.IntegerField()),
                ('allenatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to=settings.AUTH_USER_MODEL)),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='astatracking.player_quotes')),
            ],
        ),
        migrations.CreateModel(
            name='AstaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_corso', models.BooleanField(default=False)),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocatoreastacorrente', to='astatracking.player_quotes')),
            ],
        ),
    ]
